import PageBreak from '@/components/ui/PageBreak'
import { PDFLink } from '@/components/nav/Links'
import { GAME } from '@/lib/config/game_config'
import { generatePageMetadata } from '@/lib/utils/generateMetadata'
import { FactionService, SquadTypeService } from '@/services'
import { ScriptedOperations } from '@/data/scriptedoperations'
import { MissionBattlefields } from '@/data/mission_battlefields'
import { MissionObjectives } from '@/data/mission_objectives'
import { MissionDeployments } from '@/data/mission_deployments'
import OperationCard from './operation-card'

export async function generateMetadata() {
  return generatePageMetadata({
    title: 'Scripted Operations',
    description: `Authored PvE Operations for ${GAME.NAME}, a free miniatures sci-fi skirmish wargame.`,
    images: [{ url: '/icons/icon-big.png', width: 512, height: 512 }],
    keywords: ['free', 'rules', 'operations', 'campaigns', 'missions', 'pdf', 'pve'],
    pagePath: '/rules/scriptedoperations'
  })
}

export default async function RuleBookOperations() {
  const versionTimestamp = new Intl.DateTimeFormat('en-CA', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  }).format(new Date()).replaceAll('-', '')

  const factions = await FactionService.getAllFactions()
  const squadTypes = await SquadTypeService.getAllSquadTypes()

  // Lookups to resolve the IDs stored on each Operation into printable titles.
  const factionNames = new Map(factions.map((f) => [f.factionId, f.factionName]))
  const squadTypeNames = new Map(squadTypes.map((st) => [st.squadTypeId, st.squadTypeName]))
  const battlefieldTitles = new Map(MissionBattlefields.map((b) => [b.battlefieldId, b.title]))
  const deploymentTitles = new Map(MissionDeployments.map((d) => [d.deploymentId, d.title]))
  const objectives = new Map(
    MissionObjectives.flatMap((archetype) =>
      archetype.variations.map((v) => [v.objectiveId, { archetype: archetype.title, title: v.title }] as const)
    )
  )

  // Operations grouped by the Faction the player runs them as, in faction seq order.
  const operationsByFaction = factions
    .slice()
    .sort((a, b) => a.seq - b.seq)
    .map((faction) => ({
      faction,
      operations: ScriptedOperations.filter((op) => op.playerFactionId === faction.factionId),
    }))
    .filter((group) => group.operations.length > 0)

  return (
    <>
      {/* Cover */}
      <img src="/img/rules/BookCoverAlt.webp" className="printonly fullpage overflow-y-hidden" style={{pageBreakAfter: 'always'}} loading="eager" decoding="async" />
      <div className="printonly absolute left-1/2 top-1/4 -translate-x-1/2">
        <div className="text-center text-white font-title text-2xl tracking-wide bg-black/70 px-6 py-3 rounded-lg shadow-lg">
          <h1>Pve Scripted Operations</h1>
          <p className="text-md">
            2nd Edition <span className="text-sm">v{versionTimestamp}</span>
          </p>
        </div>
      </div>

      <div className="rules px-3 max-w-7xl mx-auto">
        {/* Intro */}
        <div className="section">
          <h1 className="text-center pt-48 mb-12 font-title" id="operations" style={{position: 'relative', top: '50%' }}>
            PvE Scripted Operations
          </h1>

          <div className="section twocols">
            <div className="section">
              <h2>About</h2>
              <p className="mb-4">
                An <strong>Operation</strong> is a three-Mission deployment arc played against a single NPC faction.
                Where a standard PvE Mission is generated by rolling for its Battlefield, Deployment, and Objectives, the Operations in this book are <em>authored</em>:
                each one fixes those choices in advance and wraps them in a short narrative thread, so the three Missions read as one continuous engagement rather than three unrelated fights.
              </p>
              <p className="mb-4">
                Every playable faction has one Operation against each faction in the galaxy, including its own.
                Choose the Operation that matches the Faction you are playing and the enemy you want to fight, then run its three Missions in order.
              </p>
              <em>
                Note you will need the <PDFLink href="/assets/books/Core Rules - Ruinstars.pdf" title='Core Rules' /> and the <PDFLink href="/assets/books/Missions - Ruinstars.pdf" title='Missions' /> books to play these Operations.
              </em>
            </div>
          
            <div className="section">
              <h2>Running an Operation</h2>
              <p>
                Each Operation entry lists the enemy <strong>Faction</strong> and the <strong>Squad Type</strong> to build its NPC Squad from, a single <strong>Battlefield</strong> used for all three Missions, and, for each Mission, a fixed <strong>Objective</strong> and <strong>Deployment</strong>.
                <br />
                The listed objective is the <strong>Primary Objective</strong>; it must be completed to proceed to the next Mission in the Operation. 
                Roll a second, random <strong>Secondary Objective</strong> at the start of the Mission. That Secondary Objective must be of a different Archetype than the Primary Objective.
              </p>
              <p>
                Set up each Mission as described in the Missions book, using the provided Battlefield, Objective, and Deployment isntead of the usual rolls.
                All other rules are unchanged: Battlefield effects still trigger each Turn, Objectives are scored normally, and Mission scoring works as it does in any PvE Mission.
              </p>
              <p>
                Every Operation uses one <strong>Control</strong>, one <strong>Activate</strong>, and one <strong>Destroy</strong> Objective across its three Missions, and never repeats a Deployment.
                Expect each Operation to demand a Squad that can hold ground, work an objective, and break a target.
              </p>
            </div>
          </div>
          <div className="section twocols">
            <div className="section">
              <div className="section border border-main rounded-md px-6 py-2">
                <h4>Operation Sequence</h4>
                <ol className="ml-4">
                  <li>Choose an Operation for your Faction</li>
                  <li>Set the Threat Level</li>
                  <li>Build the NPC Squad from the listed Squad Type</li>
                  <li>Play Mission 1, 2, and 3 in order</li>
                  <li>Return to Homebase</li>
                </ol>
              </div>
            </div>
            <div className="section">
              <h3>Between Missions</h3>
              <p>
                The Squad stays deployed for all three Missions: it cannot change its Units or Gear, and MP earned during the Operation cannot be spent until it ends.
                Between Missions, remove <strong>one Injury</strong> from any one Unit in the Squad (one total, not one per Unit).
                After the third Mission, the Squad returns to Homebase as normal.
              </p>
            </div>
          </div>
        </div>

        {/* Index */}
        {/*
        <PageBreak />
        <div className="section">
          <h2>Operations Index</h2>
          <div className="section twocols">
            {operationsByFaction.map(({ faction, operations }) => (
              <div key={faction.factionId} className="section mb-3">
                <h4>{faction.factionName}</h4>
                <table>
                  <thead>
                    <tr>
                      <th>Operation</th>
                      <th>Enemy Squad</th>
                      <th>Battlefield</th>
                      <th>Objectives</th>
                    </tr>
                  </thead>
                  <tbody>
                    {operations.map((op) => (
                      <tr key={op.operationId}>
                        <td><strong>{op.title}</strong></td>
                        <td>{squadTypeNames.get(op.npcSquadTypeId) ?? op.npcSquadTypeId}</td>
                        <td>{battlefieldTitles.get(op.battlefieldId) ?? op.battlefieldId}</td>
                        <td className="text-main">{op.missions.map((m) => m.objectiveId).join(' ')}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ))}
          </div>
        </div>
        */}

        {/* Operations */}
        {operationsByFaction.map(({ faction, operations }) => (
          <div key={faction.factionId}>
            <PageBreak />
            <div className="section">
              <h2 id={`ops-${faction.factionId.toLowerCase()}`}>{faction.factionName}</h2>
              <p className="text-center"><em>{faction.tagline}</em></p>
              <div className="operations-grid">
                {operations.map((op) => (
                  <OperationCard
                    key={op.operationId}
                    operationId={op.operationId}
                    title={op.title}
                    npcFactionName={factionNames.get(op.npcFactionId) ?? op.npcFactionId}
                    npcSquadTypeName={squadTypeNames.get(op.npcSquadTypeId) ?? op.npcSquadTypeId}
                    battlefieldTitle={battlefieldTitles.get(op.battlefieldId) ?? op.battlefieldId}
                    description={op.description}
                    missions={op.missions.map((m) => ({
                      seq: m.seq,
                      title: m.title,
                      description: m.description,
                      objectiveId: m.objectiveId,
                      objectiveArchetype: objectives.get(m.objectiveId)?.archetype ?? '',
                      objectiveTitle: objectives.get(m.objectiveId)?.title ?? m.objectiveId,
                      deploymentId: m.deploymentId,
                      deploymentTitle: deploymentTitles.get(m.deploymentId) ?? m.deploymentId,
                    }))}
                  />
                ))}
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  )
}
