import { getRandom } from '../utils/utils'

export function name_aesbaer() {
  const names1 = ['Aes','Ar\'o','Ar\'ug','Arh','Arma','Arqa','Arzo','Arzur','Asdru','Bahr','Bahru','Baze','Bazha','Bernu','Bhu','Bra','Braes','Bura','Caen','Char','Cra\'oza','Crahl','Daza','Dra','Draz','Duhr','El\'ur','Erza','Ez','Ezar','Fahar','Fahr','Fhars','Frae','Fure','Ga\'on','Gahu','Gara','Gra','Griza','Gura','Id\'ar','Iru','Iys','Izen','Izra','Kae','Kahar','Kahr','Khan','Kyra','Laerh','Lahza','Laku','Laza','Le\'u','Maru','Masra','Mazro','Meza','Mo\'u','Much','Muri','Or\'i','Ori','Orqa','Oura','Ozu','Taga','Tah','Teza','Trazh','Yl\'a','Yra','Yzu', 'Aes','Aezo','Ahl','Al\'o','Ar\'us','Ara','Arqi','Arze','Ashru','Baeh','Baes','Bahre','Belze','Besnu','Bezha','Bhi','Bhra','Bira','Caren','Cher','Crehn','Cri\'ora','Dehza','Der','Dera','Drehz','Ehz','El\'or','Eraza','Ezir','Fehsa','Fera','Fha','Fihr','Frae','Gae\'en','Gahnu','Garia','Gri','Grihza','Gura','Iaze','Ide\'a','Ire','Iyes','Izera','Kaera','Kahna','Kehna','Khel','Kihre','Lae\'o','Laerh','Laeza','Lanu','Lohza','Maero','Meha','Mera','Meri','Mero\'a','Mesra','Mihza','Ohza','Ora','Ora\'i','Ori','Oriqa','Taza','Teha','Tera','Trezh','Yna','Yr\'a','Yzi']
  const names2 = ['baehr','bran','braq','bros','bryn','dazar','dhar','diaq','dovur','dros','durin','gahn','gard','gran','grath','hiron','his','hyque','kei','kos','kras','kyth','mahr','maq','mar','mass','mien','moque','mor','naer','nahr','nazar','neque','nyr','qar','qir','ra','rad','raes','ras','rath','raz','riaq','rihz','rior','rizar','ruin','ryq','sar','sarith','saros','sath','shar','sque','stra','syr','tahr','taz','teque','thara','tharn','tiron','tyhr','tzar','vall','van','vhar','vor','vyn','zaen','zaq','zhan','zhar','zon','zyth', 'baehra','brique','bris','brynn','daque','dera','deza','dhae','dove','dreos','gahne','geza','gohne','grynn','gwyss','heque','hia','hira','keo','keri','kryss','kysse','maque','mare','mea','mehra','mirenne','mohre','myss','naehr','nahra','neque','neza','nyrr','qinn','qore','rae','raesh','reah','reaq','renar','renn','resse','rihque','rith','riza','rizora','runae','saer','sarihs','seos','seqe','seth','sher','shi','sira','syrr','taena','taez','tarin','teque','thara','thera','tihr','tyhs','vaesh','velle','vero','vynn','zae','zaehn','zhael','zhenne','zoh','zysh']
  
  const part1 = getRandom(names1) // Get a random name from the first part
  const part2 = getRandom(names2) // Get a random name from the second part
  
  return `${part1}${part2}`
}